import type { Stage } from "./engine";

export const STAGES: Stage[] = [
  {
    id: 1,
    name: "野良猫",
    hp: 30,
    ai: "random",
    description: "ゴミ箱を漁る自由人。",
    categories: ["生物","日常","自然","食べ物"],
    rarities: ["common"],
    deckSize: 15,
  },
  {
    id: 2,
    name: "嵐",
    hp: 40,
    ai: "random",
    description: "自然の猛威。",
    categories: ["自然","災害"],
    rarities: ["common","rare"],
    deckSize: 15,
  },
  {
    id: 3,
    name: "暴走族",
    hp: 50,
    ai: "aggressive",
    description: "攻撃カードを優先的に出す。",
    categories: ["道具","現代","兵器"],
    rarities: ["common","rare"],
    deckSize: 18,
  },
  {
    id: 4,
    name: "熊",
    hp: 60,
    ai: "highAtk",
    description: "手札中で最も攻撃力が高いカードを出す。",
    categories: ["生物","自然"],
    rarities: ["common","rare"],
    deckSize: 18,
  },
  {
    id: 5,
    name: "軍隊",
    hp: 80,
    ai: "counter",
    description: "直前のプレイヤーの手に強いカードを選ぶ。",
    categories: ["兵器","道具","テクノロジー"],
    rarities: ["rare","epic"],
    deckSize: 20,
  },
  {
    id: 6,
    name: "ドラゴン",
    hp: 100,
    ai: "balanced",
    description: "攻撃と回復をバランスよく使う。",
    categories: ["災害","宇宙","自然"],
    rarities: ["rare","epic"],
    deckSize: 20,
  },
  {
    id: 7,
    name: "AI",
    hp: 80,
    ai: "adaptive",
    description: "プレイヤーのカード使用傾向を学習して対策する。",
    categories: ["テクノロジー","現代","兵器"],
    rarities: ["rare","epic"],
    deckSize: 20,
  },
  {
    id: 8,
    name: "神",
    hp: 120,
    ai: "optimal",
    description: "常に手札の中から最適なカードを出す。",
    categories: ["概念","宇宙"],
    rarities: ["epic","legendary"],
    deckSize: 20,
  },
  {
    id: 9,
    name: "宇宙",
    hp: 150,
    ai: "optimal",
    description: "全てを内包する最終試練。",
    categories: ["宇宙","概念","災害","兵器"],
    rarities: ["epic","legendary","mythic"],
    deckSize: 20,
  },
  {
    id: 10,
    name: "???",
    hp: 100,
    ai: "mirror",
    description: "最大の敵は、自分自身。",
    categories: [],
    rarities: ["common","rare","epic","legendary","mythic"],
    deckSize: 20,
  },
];
